WT_PROJECT/authentication/groups/urls.py
from django.conf.urls import url

from . import views

app_name = 'groups'

urlpatterns = [
    url("^$", views.ListGroups.as_view(), name="all"),
    url("^new/$", views.CreateGroup.as_view(), name="create"),
    url("^posts/in/(?P<slug>[-\w]+)/$",views.SingleGroup.as_view(),name="single"),
    url("join/(?P<slug>[-\w]+)/$",views.JoinGroup.as_view(),name="join"),
    url("leave/(?P<slug>[-\w]+)/$",views.LeaveGroup.as_view(),name="leave"),
]

WT_PROJECT/authentication/posts/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name='posts'

urlpatterns = [
    url("^$", views.PostList.as_view(), name="all"),
    url("new/$", views.CreatePost.as_view(), name="create"),
    url("by/(?P<username>[-\w]+)/$",views.UserPosts.as_view(),name="for_user"),
    url("by/(?P<username>[-\w]+)/(?P<pk>\d+)/$",views.PostDetail.as_view(),name="single"),
    url("delete/(?P<pk>\d+)/$",views.DeletePost.as_view(),name="delete"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.STATIC_URL,document_root=settings.MEDIA_ROOT)

authentication/authentication/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

myDjangoProject/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

WT_PROJECT/authentication/groups/models.py
from django.conf import settings
from django.urls import reverse
from django.db import models
from django.utils.text import slugify
from log_app.models import User

import misaka

from django.contrib.auth import get_user_model
User = get_user_model()

# https://docs.djangoproject.com/en/1.11/howto/custom-template-tags/#inclusion-tags
# This is for the in_group_members check template tag
from django import template
register = template.Library()



class Group(models.Model):
    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(allow_unicode=True, unique=True)
    description = models.TextField(blank=True, default='')
    description_html = models.TextField(editable=False, default='', blank=True)
    members = models.ManyToManyField(User,through="GroupMember")
    

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        self.description_html = misaka.html(self.description)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("groups:single", kwargs={"slug": self.slug})


    class Meta:
        ordering = ["name"]


class GroupMember(models.Model):
    group = models.ForeignKey(Group, related_name="memberships",on_delete=models.CASCADE,)
    user = models.ForeignKey(User,related_name='user_groups',on_delete=models.CASCADE,)

    def __str__(self):
        return self.user.username

    class Meta:
        unique_together = ("group", "user")

WT_PROJECT/authentication/log_app/models.py
from django.contrib import auth
from django.db import models
from django.utils import timezone


class User(auth.models.User, auth.models.PermissionsMixin):
    
    def __str__(self):
        return "@{}".format(self.username)

WT_PROJECT/authentication/posts/models.py
from django.conf import settings
from django.db.models.deletion import CASCADE
from django.urls import reverse
from django.db import models
from groups.models import GroupMember

import misaka

from groups.models import  Group

from django.contrib.auth import get_user_model
User = get_user_model()


class Post(models.Model):
    user = models.ForeignKey(User, related_name="posts",on_delete=models.CASCADE,)
    created_at = models.DateTimeField(auto_now=True)
    message = models.TextField()
    message_html = models.TextField(editable=False)
    group = models.ForeignKey(Group, related_name="posts",null=True, blank=True,on_delete=models.CASCADE,)
    post_image=models.ImageField(null=True,blank=True,upload_to='images/')

    def __str__(self):
        return self.message

    def save(self, *args, **kwargs):
        self.message_html = misaka.html(self.message)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("posts:single",kwargs={"username": self.user.username,"pk": self.pk})

    class Meta:
        ordering = ["-created_at"]
        unique_together = ["user", "message"]

WT_PROJECT/authentication/log_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegisterUserForm(UserCreationForm):
    email=forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control'}))
    first_name=forms.CharField(max_length=30,widget=forms.EmailInput(attrs={'class':'form-control'}))
    last_name=forms.CharField(max_length=30,widget=forms.EmailInput(attrs={'class':'form-control'}))
    class Meta:
        model = User
        fields=('username','first_name','last_name','email','password1','password2')
    def __init__(self, *args, **kwargs) :
        super(RegisterUserForm,self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs['class'] = 'form-conrol'
        self.fields['password1'].widget.attrs['class'] = 'form-conrol'
        self.fields['password2'].widget.attrs['class'] = 'form-conrol'
        

WT_PROJECT/authentication/posts/forms.py
from django import forms

from posts import models


class PostForm(forms.ModelForm):
    class Meta:
        fields = ("message",'post_image',"group")
        model = models.Post

    def __init__(self, *args, **kwargs):
        user = kwargs.pop("user", None)
        super().__init__(*args, **kwargs)
        if user is not None:
            self.fields["group"].queryset = models.Group.objects.filter(members = user)

WT_PROJECT/authentication/groups/views.py
from django.contrib import messages
from django.contrib.auth.mixins import(
    LoginRequiredMixin,
    PermissionRequiredMixin
)

from django.urls import reverse
from django.db import IntegrityError
from django.shortcuts import get_object_or_404
from django.views import generic
from groups.models import Group,GroupMember
from . import models

class CreateGroup(LoginRequiredMixin, generic.CreateView):
    fields = ("name", "description")
    model = Group

class SingleGroup(generic.DetailView):
    model = Group

class ListGroups(generic.ListView):
    model = Group


class JoinGroup(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse("groups:single",kwargs={"slug": self.kwargs.get("slug")})

    def get(self, request, *args, **kwargs):
        group = get_object_or_404(Group,slug=self.kwargs.get("slug"))

        try:
            GroupMember.objects.create(user=self.request.user,group=group)

        except IntegrityError:
            messages.warning(self.request,("Warning, already a member of {}".format(group.name)))

        else:
            messages.success(self.request,"You are now a member of the {} group.".format(group.name))

        return super().get(request, *args, **kwargs)


class LeaveGroup(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse("groups:single",kwargs={"slug": self.kwargs.get("slug")})

    def get(self, request, *args, **kwargs):

        try:

            membership = models.GroupMember.objects.filter(
                user=self.request.user,
                group__slug=self.kwargs.get("slug")
            ).get()

        except models.GroupMember.DoesNotExist:
            messages.warning(
                self.request,
                "You can't leave this group because you aren't in it."
            )
        else:
            membership.delete()
            messages.success(
                self.request,
                "You have successfully left this group."
            )
        return super().get(request, *args, **kwargs)

WT_PROJECT/authentication/log_app/views.py
from django.shortcuts import render,HttpResponse,redirect
from django.contrib.auth import authenticate, login ,logout
from django.contrib.auth.forms import UserCreationForm
from .forms import RegisterUserForm
from django.contrib import messages
from django.contrib.auth.models import User

# Create your views here.

def home(request):
    return render(request,'home.html')

def signup(request):
 
    if request.user.is_authenticated:
        return redirect('home')
    else:
        form=RegisterUserForm
        if request.method=='POST':
            form= RegisterUserForm(request.POST)
            if form.is_valid():
                form.save()
                user=form.cleaned_data.get('username')
                messages.successs(request, 'Account was created for ' + user)
                return redirect('login')

        context= {'form': form}
        return render(request, 'signup.html' , context)

def login_user(request):
    if request.method=='POST':
        username = request.POST['username']
        password = request.POST['password']
        User = authenticate(request, username=username, password=password)
        if User is not None:
            login(request, User)
            return redirect('home')
        else:
            messages.success(request, 'Wrong Username or Password. Try again.')
            return redirect('login')
    else:
        return render(request,'login.html')


def logout_user(request):
    logout(request)
    return redirect('home')

WT_PROJECT/authentication/posts/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin

from django.urls import reverse_lazy
from django.http import Http404
from django.views import generic

from braces.views import SelectRelatedMixin

from . import forms
from . import models
from django.contrib.auth import get_user_model
User = get_user_model()


class PostList(SelectRelatedMixin, generic.ListView):
    model = models.Post
    select_related = ("user", "group")


class UserPosts(generic.ListView):
    model = models.Post
    template_name = "posts/user_post_list.html"

    def get_queryset(self):
        try:
            self.post_user = User.objects.prefetch_related("posts").get(
                username__iexact=self.kwargs.get("username")
            )
        except User.DoesNotExist:
            raise Http404
        else:
            return self.post_user.posts.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["post_user"] = self.post_user
        return context


class PostDetail(SelectRelatedMixin, generic.DetailView):
    model = models.Post
    select_related = ("user", "group")

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(
            user__username__iexact=self.kwargs.get("username")
        )


class CreatePost(LoginRequiredMixin, SelectRelatedMixin, generic.CreateView):
    form_class = forms.PostForm
    model = models.Post

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({"user": self.request.user})
        return kwargs

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)



class DeletePost(LoginRequiredMixin, SelectRelatedMixin, generic.DeleteView):
    model = models.Post
    select_related = ("user", "group")
    success_url = reverse_lazy("posts:all")

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id=self.request.user.id)

    def delete(self, *args, **kwargs):
        messages.success(self.request, "Post Deleted")
        return super().delete(*args, **kwargs)

WT_PROJECT/authentication/templates/base.html
{% load static %}


<!doctype html>
<html lang="en">
  <head>
    <title>{% 
    {% block tittle %}
        
    {% endblock tittle %}
         %}</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    
    <!-- Bootstrap CSS -->
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

    <!-- <link rel="stylesheet" href="{% static '/master.css' %}"> -->
    <!-- <link rel="stylesheet" href="{% static '/zip/master1.css' %}"> -->

  </head>
  <body>

    {% include 'nav.html' %}
    
      
      
    

    {% block content %}
        
    {% endblock content %}
    <br><br><br><br><br>
    <!-- Footer -->
<footer class="page-footer font-small">

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2021 Copyright:
    <a href="{% url 'home' %}"> Social.com</a>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->
    <!-- <canvas id="canvas"></canvas> -->
      <!-- <script  src="{% static '/zip/master.js' %}"> -->
      <!-- </script> -->
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

WT_PROJECT/authentication/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block tittle %}
    HOME
{% endblock %}
    

{% block content %}


{% if user.is_authenticated %}
<img style="width: 100%; height:650px;" src="{% static '/merakist-CNbRsQj8mHQ-unsplash.jpg' %}" alt="">
<h2 style="text-align: center;">Welcome {{user.username}} To Social Website</h2>
<p style="text-align: center;">Use NavBar To <a href="{% url 'posts:all' %}">Start</a> Today With Us</p>
{% else %}
<h2 style="text-align: center;">Login or SignUp to continue</h2>
{% endif %}
    

    
    

        
    
{% endblock content %}
    

WT_PROJECT/authentication/templates/login.html
{% extends 'base.html' %}


{% block tittle %}
    LOGIN
{% endblock tittle %}
    
{% block content %}
<h1 style="margin-left:325px;">LOGIN PAGE</h1>  
<!-- <div class="container"> 
{% if messages %}
    {% for message in messages %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert">

      {{ message }}
    </div>
    
    {% endfor %}
{% endif %} 
</div> -->
<div class="shadow p-4 mb-5 bg-body rounded" style="width: 600px; margin-left:150px;">
<form method='POST'>
    {% csrf_token %}
    <div class="mb-3">
      <label for="username" class="form-label">Username</label>
      <input type="text" class="form-control" id="username" name="username" placeholder="Enter Your User Name">
    </div>
    <div class="mb-3">
      <label for="password1" class="form-label">Password</label>
      <input type="password" class="form-control" id="password1" name="password" placeholder="Enter Your Password">
    </div>
    <button type="submit" class="btn btn-primary" style="margin-left: 240px;">Login</button>
  </form>
</div>



{% endblock content %}
    

WT_PROJECT/authentication/templates/nav.html
<nav class="navbar navbar-expand-lg sticky-top navbar-dark bg-dark">
    <div class="container-fluid">
      
      <a class="navbar-brand" href="{% url 'home' %}" style="font-size: 2em;"><b>Social</b></a>
      
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
        <ul class="navbar navbar-nav navbar-right">
        {% if user.is_authenticated %}
        <li class="nav-item"><a class="nav-link" href="{% url 'posts:all' %}">NewsFeed</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'groups:all' %}">Groups</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'posts:create' %}">Create Post</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'groups:create' %}">Create Groups</a></li>
        <li class="nav-item"><button class="btn btn-outline-danger my-2 my-sm-0"><a href="{% url 'logout' %}"style="color: red">LOGOUT</a></button></li>
        <!-- <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}">Logout</a></li> -->

        {% else %}
        
        <li class="nav-item"><a class="nav-link" href="{% url 'login' %}">Login</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'signup' %}">Sign Up</a></li>

        {% endif %}

        </ul>
      </div>
    </div>
  </nav>

WT_PROJECT/authentication/templates/signup.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}


{% block tittle %}
SIGN UP
{% endblock %}

{% block content %}
<h1 style="margin-left:300px;">SIGN UP PAGE</h1>
<div class="shadow p-4 mb-5 bg-body rounded" style="width: 600px; margin-left:150px;">
    <form method="POST" novalidate action="{% url 'signup' %}">
        {% csrf_token %}
        {{form|crispy}}

        <input type="submit" name='User Create'>
    </form>
</div>

<!-- <div class="container">
<form method="POST">
    {% csrf_token %}
    
    {% for feild in form %}
        <br>
        {{feild.label}}
        <br>
        {{feild}}
    {% endfor %}
    <br>
    <br>
    <input type="submit" name='SIGNUP'>
    
    </form>
</div> -->
{% endblock content %}